### ISSUE TITLE
[folding] Collapse ending brace to the same line

### ISSUE THREAD

**Issue by superastorh** [zokugun/MrCode#1]
this bug in https://github.com/Microsoft/vscode/issues/3352

I need make it builtin

**Comment by daiyam** [comment]
@superastorh I've done the branch ` fold-last-line` which has the option `editor.showFoldingLastLine`. Can you test it?

**Comment by daiyam** [comment]
@superastorh I've updated the last release (You will need to re-download the app if you have already downloaded it)
With the setting `"editor.showFoldingLastLine": false`, you will be able to hide the last line of a folding range.
