### ISSUE TITLE
moalamri comment on May 10

### ISSUE THREAD

**Issue by softorangetech11** [zokugun/MrCode#12]
Hi,
I  happened to be looking for extension/method/hack that allows me to have folding function within a line content, for example when using utility classes in html such as Tailwind css, the line gets bigger and bigger, making it difficult to read the code with some modern framework. It could be awesome to have something like this: 
```html
<div class="...">
      <div class="..."></div>
</div>
```

Also I found this git that demonstrate the action:
![101728151-c98ac480-3aad-11eb-9790-abc8e61b11de](https://user-images.githubusercontent.com/964077/167620078-4d44c821-2497-4462-b8a4-bd987780d744.gif)

I don't know if this is achievable with MrCode, as it may require some API changing since such core function doesn't exist.

Thank you :)

_Originally posted by @moalamri in https://github.com/zokugun/MrCode/issues/6#issuecomment-1122286345_

**Comment by moalamri** [comment]
I've made an extension that make inline folding possible:

[Inline Fold](https://marketplace.visualstudio.com/items?itemName=moalamri.inline-fold)

**Comment by softorangetech11** [comment]
@moalamri Thanks for clarifying. I have closed this issue for you.
