### ISSUE TITLE
Build does not build on my arm64 system

### ISSUE THREAD

**Issue by ashirviskas** [zokugun/MrCode#4]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/11985242/136096590-e5ba6ded-f1ef-48cd-adba-cffda0e589c2.png)

**Comment by daiyam** [comment]
I've made the necessary changes so you shouldn't have the error anymore.

**Comment by ashirviskas** [comment]
@daiyam Sorry for not getting back to you sooner, I ran into other issues. Basically, I was trying to get it running on Android using termux and arch linux installation, but it just wasn't working.

For now I'll just close the issue until I get back to it. Thanks for all the help!

**Comment by daiyam** [comment]
NP. It seems like you would have an issue with the remote extensions...

**Comment by ashirviskas** [comment]
I've actually just tried it and it works! Thanks again
